use macroquad::color::Color;
use crate::module::VehicleVisualType;
use crate::ui::menu::CarChoice;

/// Complete real-world motorsport car model definition.
#[derive(Debug, Clone)]
pub struct RealCarModel {
    pub id: &'static str,
    pub name: &'static str,
    pub manufacturer: &'static str,
    pub year: u16,
    pub module_id: &'static str,
    pub category_name: &'static str,
    pub tier: u8, // 1..=5
    pub bhp: u16,
    pub torque_nm: u16,
    pub weight_kg: u16,
    pub top_speed_kmh: u16,
    pub accel_0_100: f32,
    pub drivetrain: &'static str, // "RWD", "AWD", "FWD", "4WD"
    pub engine_desc: &'static str,
    pub aero_downforce: &'static str,
    pub brakes_desc: &'static str,
    pub history_bio: &'static str,
    /// Normalized performance ratings: (Speed, Accel, Grip, Drift/Agility, Brake, Aero) [0.0..1.0]
    pub stats: (f32, f32, f32, f32, f32, f32),
    pub visual_type: VehicleVisualType,
    pub base_car_choice: CarChoice,
    pub primary_color: Color,
    pub secondary_color: Color,
}

impl RealCarModel {
    /// Checks whether this vehicle is eligible for a race with a required category/tier.
    /// Rule: Selectable iff car.tier <= race_required_tier || dev_mode.
    #[inline]
    pub fn is_eligible_for_race(&self, race_required_tier: u8, dev_mode: bool) -> bool {
        dev_mode || self.tier <= race_required_tier
    }
}

/// Master catalog of all authentic motorsport vehicles in TdRace.
pub static ALL_REAL_CARS: &[RealCarModel] = &[
    // =========================================================================
    // MODULE 1: GRAN TURISMO & ENDURANCE GT
    // =========================================================================
    // Tier 1: GT4 Clubsport
    RealCarModel {
        id: "gt_porsche_718_gt4",
        name: "Porsche 718 Cayman GT4 RS Clubsport",
        manufacturer: "Porsche",
        year: 2022,
        module_id: "gt",
        category_name: "GT4 Clubsport",
        tier: 1,
        bhp: 500,
        torque_nm: 450,
        weight_kg: 1320,
        top_speed_kmh: 304,
        accel_0_100: 3.4,
        drivetrain: "RWD",
        engine_desc: "4.0L NA Flat-6 @ 9,000 RPM",
        aero_downforce: "Cl 0.85 / Cd 0.42",
        brakes_desc: "Steel 380mm 6-Piston Monobloc",
        history_bio: "Mid-engine benchmark of customer racing. Introduced in 2022 featuring the screaming 911 GT3 engine, delivering surgical balance and razor-sharp apex turn-in.",
        stats: (0.78, 0.82, 0.85, 0.70, 0.82, 0.65),
        visual_type: VehicleVisualType::TouringGT { widebody: false, gt_wing: true, diffuser: false },
        base_car_choice: CarChoice::GT4Clubsport,
        primary_color: Color::new(0.85, 0.88, 0.92, 1.0),
        secondary_color: Color::new(0.08, 0.08, 0.12, 1.0),
    },
    RealCarModel {
        id: "gt_bmw_m4_gt4",
        name: "BMW M4 GT4 (G82)",
        manufacturer: "BMW",
        year: 2023,
        module_id: "gt",
        category_name: "GT4 Clubsport",
        tier: 1,
        bhp: 450,
        torque_nm: 650,
        weight_kg: 1380,
        top_speed_kmh: 280,
        accel_0_100: 3.6,
        drivetrain: "RWD",
        engine_desc: "3.0L M TwinPower Turbo I6",
        aero_downforce: "Cl 0.82 / Cd 0.44",
        brakes_desc: "Steel 390mm 6-Piston AP Racing",
        history_bio: "Customer racing workhorse built on the G82 chassis. Renowned for its curb compliance, high mechanical grip, and massive twin-turbo mid-range punch.",
        stats: (0.76, 0.85, 0.82, 0.68, 0.80, 0.62),
        visual_type: VehicleVisualType::TouringGT { widebody: false, gt_wing: true, diffuser: false },
        base_car_choice: CarChoice::GT4Clubsport,
        primary_color: Color::new(0.15, 0.35, 0.85, 1.0),
        secondary_color: Color::new(0.95, 0.20, 0.20, 1.0),
    },
    RealCarModel {
        id: "gt_aston_vantage_gt4",
        name: "Aston Martin Vantage AMR GT4",
        manufacturer: "Aston Martin",
        year: 2021,
        module_id: "gt",
        category_name: "GT4 Clubsport",
        tier: 1,
        bhp: 470,
        torque_nm: 630,
        weight_kg: 1370,
        top_speed_kmh: 285,
        accel_0_100: 3.5,
        drivetrain: "RWD",
        engine_desc: "4.0L Twin-Turbo V8",
        aero_downforce: "Cl 0.84 / Cd 0.43",
        brakes_desc: "Steel 380mm 6-Piston",
        history_bio: "Built at Prodrive in Banbury. Features perfect 50:50 weight distribution and a progressive V8 torque curve that forgivingly absorbs aggressive trail-braking.",
        stats: (0.77, 0.83, 0.84, 0.72, 0.81, 0.64),
        visual_type: VehicleVisualType::TouringGT { widebody: false, gt_wing: true, diffuser: false },
        base_car_choice: CarChoice::GT4Clubsport,
        primary_color: Color::new(0.12, 0.45, 0.28, 1.0),
        secondary_color: Color::new(0.85, 0.95, 0.20, 1.0),
    },
    RealCarModel {
        id: "gt_toyota_supra_gt4",
        name: "Toyota GR Supra GT4 EVO",
        manufacturer: "Toyota",
        year: 2023,
        module_id: "gt",
        category_name: "GT4 Clubsport",
        tier: 1,
        bhp: 430,
        torque_nm: 660,
        weight_kg: 1300,
        top_speed_kmh: 275,
        accel_0_100: 3.5,
        drivetrain: "RWD",
        engine_desc: "3.0L Twin-Scroll Turbo I6",
        aero_downforce: "Cl 0.80 / Cd 0.41",
        brakes_desc: "Brembo Racing 6-Piston",
        history_bio: "Lightest car in the GT4 field with upgraded EVO braking and revised damper curves, providing lightning deceleration into tight chicanes.",
        stats: (0.75, 0.84, 0.86, 0.74, 0.84, 0.60),
        visual_type: VehicleVisualType::TouringGT { widebody: false, gt_wing: true, diffuser: false },
        base_car_choice: CarChoice::GT4Clubsport,
        primary_color: Color::new(0.85, 0.15, 0.15, 1.0),
        secondary_color: Color::new(0.10, 0.10, 0.12, 1.0),
    },

    // Tier 2: GT3 Evo / FIA GT3
    RealCarModel {
        id: "gt_porsche_911_gt3r",
        name: "Porsche 911 GT3 R (992)",
        manufacturer: "Porsche",
        year: 2023,
        module_id: "gt",
        category_name: "GT3 Evo / FIA GT3",
        tier: 2,
        bhp: 565,
        torque_nm: 465,
        weight_kg: 1250,
        top_speed_kmh: 298,
        accel_0_100: 2.9,
        drivetrain: "RWD",
        engine_desc: "4.2L NA Water-Cooled Flat-6 @ 9,250 RPM",
        aero_downforce: "Cl 2.10 / Cd 0.62",
        brakes_desc: "Monobloc Carbon-Ceramic 6-Piston",
        history_bio: "The global benchmark rear-engine GT3 racer. Renowned for supreme corner-exit traction and high-speed trail-braking pivot capability.",
        stats: (0.91, 0.93, 0.95, 0.55, 0.94, 0.92),
        visual_type: VehicleVisualType::TouringGT { widebody: true, gt_wing: true, diffuser: true },
        base_car_choice: CarChoice::GT3Car,
        primary_color: Color::new(0.90, 0.90, 0.92, 1.0),
        secondary_color: Color::new(0.90, 0.20, 0.10, 1.0),
    },
    RealCarModel {
        id: "gt_ferrari_296_gt3",
        name: "Ferrari 296 GT3",
        manufacturer: "Ferrari",
        year: 2023,
        module_id: "gt",
        category_name: "GT3 Evo / FIA GT3",
        tier: 2,
        bhp: 600,
        torque_nm: 712,
        weight_kg: 1265,
        top_speed_kmh: 301,
        accel_0_100: 2.8,
        drivetrain: "RWD",
        engine_desc: "3.0L 120° Twin-Turbo V6",
        aero_downforce: "Cl 2.20 / Cd 0.64",
        brakes_desc: "Brembo Monobloc 6-Piston",
        history_bio: "Succeeded the 488 GT3. Powered by a 120° Hot-V turbo V6. Claimed overall victory at the 2023 Nürburgring 24 Hours on its debut endurance season.",
        stats: (0.94, 0.96, 0.95, 0.52, 0.93, 0.94),
        visual_type: VehicleVisualType::TouringGT { widebody: true, gt_wing: true, diffuser: true },
        base_car_choice: CarChoice::GT3Car,
        primary_color: Color::new(0.85, 0.08, 0.08, 1.0),
        secondary_color: Color::new(1.0, 0.85, 0.10, 1.0),
    },
    RealCarModel {
        id: "gt_amg_gt3_evo",
        name: "Mercedes-AMG GT3 Evo",
        manufacturer: "Mercedes-AMG",
        year: 2020,
        module_id: "gt",
        category_name: "GT3 Evo / FIA GT3",
        tier: 2,
        bhp: 550,
        torque_nm: 650,
        weight_kg: 1285,
        top_speed_kmh: 295,
        accel_0_100: 3.0,
        drivetrain: "RWD",
        engine_desc: "6.2L Naturally Aspirated V8",
        aero_downforce: "Cl 2.05 / Cd 0.65",
        brakes_desc: "AMG Carbon 6-Piston",
        history_bio: "Front-mid mounted atmospheric 6.2L V8 monster. Celebrated for chassis stability over curbs and progressive, predictable throttle powerband.",
        stats: (0.90, 0.92, 0.93, 0.56, 0.92, 0.90),
        visual_type: VehicleVisualType::TouringGT { widebody: true, gt_wing: true, diffuser: true },
        base_car_choice: CarChoice::GT3Car,
        primary_color: Color::new(0.45, 0.48, 0.52, 1.0),
        secondary_color: Color::new(0.10, 0.85, 0.70, 1.0),
    },
    RealCarModel {
        id: "gt_audi_r8_gt3_evo2",
        name: "Audi R8 LMS GT3 Evo II",
        manufacturer: "Audi Sport",
        year: 2022,
        module_id: "gt",
        category_name: "GT3 Evo / FIA GT3",
        tier: 2,
        bhp: 585,
        torque_nm: 550,
        weight_kg: 1260,
        top_speed_kmh: 300,
        accel_0_100: 2.9,
        drivetrain: "RWD",
        engine_desc: "5.2L Naturally Aspirated V10",
        aero_downforce: "Cl 2.12 / Cd 0.63",
        brakes_desc: "Brembo Endurance Spec",
        history_bio: "Screaming naturally aspirated mid-engine V10 producing exceptional mechanical downforce and high-speed corner stability across endurance classics.",
        stats: (0.92, 0.94, 0.94, 0.53, 0.93, 0.91),
        visual_type: VehicleVisualType::TouringGT { widebody: true, gt_wing: true, diffuser: true },
        base_car_choice: CarChoice::GT3Car,
        primary_color: Color::new(0.12, 0.12, 0.15, 1.0),
        secondary_color: Color::new(0.90, 0.15, 0.15, 1.0),
    },

    // Tier 3: GT2 Biturbo / SRO GT2
    RealCarModel {
        id: "gt_porsche_911_gt2_rs",
        name: "Porsche 911 GT2 RS Clubsport",
        manufacturer: "Porsche",
        year: 2019,
        module_id: "gt",
        category_name: "GT2 Biturbo",
        tier: 3,
        bhp: 700,
        torque_nm: 750,
        weight_kg: 1390,
        top_speed_kmh: 330,
        accel_0_100: 2.7,
        drivetrain: "RWD",
        engine_desc: "3.8L Twin-Turbo Flat-6",
        aero_downforce: "Cl 1.45 / Cd 0.52",
        brakes_desc: "PCCB 390mm 6-Piston",
        history_bio: "Raw 700 BHP biturbo missile created for high-velocity sprint racing. Features enormous straight-line top speed with lower aerodynamic drag.",
        stats: (0.96, 0.97, 0.89, 0.65, 0.90, 0.78),
        visual_type: VehicleVisualType::TouringGT { widebody: true, gt_wing: true, diffuser: true },
        base_car_choice: CarChoice::GT2Biturbo,
        primary_color: Color::new(0.85, 0.85, 0.88, 1.0),
        secondary_color: Color::new(0.15, 0.15, 0.20, 1.0),
    },
    RealCarModel {
        id: "gt_brabham_bt62_gt2",
        name: "Brabham BT62 GT2",
        manufacturer: "Brabham",
        year: 2020,
        module_id: "gt",
        category_name: "GT2 Biturbo",
        tier: 3,
        bhp: 700,
        torque_nm: 667,
        weight_kg: 1100,
        top_speed_kmh: 325,
        accel_0_100: 2.6,
        drivetrain: "RWD",
        engine_desc: "5.4L NA Quad-Cam V8",
        aero_downforce: "Cl 1.65 / Cd 0.54",
        brakes_desc: "Carbon-on-Carbon 6-Piston",
        history_bio: "Ultralight carbon monocoque from the legendary motorsport dynasty, generating savage acceleration from a 5.4L atmospheric quad-cam V8.",
        stats: (0.95, 0.98, 0.92, 0.60, 0.95, 0.84),
        visual_type: VehicleVisualType::TouringGT { widebody: true, gt_wing: true, diffuser: true },
        base_car_choice: CarChoice::GT2Biturbo,
        primary_color: Color::new(0.10, 0.35, 0.20, 1.0),
        secondary_color: Color::new(0.95, 0.75, 0.10, 1.0),
    },
    RealCarModel {
        id: "gt_maserati_mc20_gt2",
        name: "Maserati MC20 GT2",
        manufacturer: "Maserati",
        year: 2023,
        module_id: "gt",
        category_name: "GT2 Biturbo",
        tier: 3,
        bhp: 621,
        torque_nm: 730,
        weight_kg: 1360,
        top_speed_kmh: 320,
        accel_0_100: 2.8,
        drivetrain: "RWD",
        engine_desc: "3.0L Nettuno Twin-Turbo V6",
        aero_downforce: "Cl 1.55 / Cd 0.53",
        brakes_desc: "Brembo Monobloc 6-Piston",
        history_bio: "Marked Maserati's triumphant return to GT racing, utilizing the patented pre-chamber twin-spark Nettuno V6 in a full carbon monocoque.",
        stats: (0.94, 0.95, 0.91, 0.62, 0.91, 0.80),
        visual_type: VehicleVisualType::TouringGT { widebody: true, gt_wing: true, diffuser: true },
        base_car_choice: CarChoice::GT2Biturbo,
        primary_color: Color::new(0.10, 0.30, 0.70, 1.0),
        secondary_color: Color::new(0.90, 0.90, 0.95, 1.0),
    },
    RealCarModel {
        id: "gt_audi_r8_gt2",
        name: "Audi R8 LMS GT2",
        manufacturer: "Audi Sport",
        year: 2020,
        module_id: "gt",
        category_name: "GT2 Biturbo",
        tier: 3,
        bhp: 640,
        torque_nm: 550,
        weight_kg: 1350,
        top_speed_kmh: 328,
        accel_0_100: 2.7,
        drivetrain: "RWD",
        engine_desc: "5.2L NA V10",
        aero_downforce: "Cl 1.40 / Cd 0.50",
        brakes_desc: "Steel 380mm 6-Piston",
        history_bio: "Most powerful customer car ever produced by Audi Sport, crowned with a dramatic roof-mounted ram-air intake snorkel for high-speed cylinder filling.",
        stats: (0.96, 0.96, 0.90, 0.64, 0.91, 0.76),
        visual_type: VehicleVisualType::TouringGT { widebody: true, gt_wing: true, diffuser: true },
        base_car_choice: CarChoice::GT2Biturbo,
        primary_color: Color::new(0.85, 0.85, 0.10, 1.0),
        secondary_color: Color::new(0.12, 0.12, 0.15, 1.0),
    },

    // Tier 4: GT1 Legend / 90s Le Mans GT1
    RealCarModel {
        id: "gt_porsche_911_gt1_98",
        name: "Porsche 911 GT1-98",
        manufacturer: "Porsche",
        year: 1998,
        module_id: "gt",
        category_name: "GT1 Legend",
        tier: 4,
        bhp: 550,
        torque_nm: 630,
        weight_kg: 950,
        top_speed_kmh: 335,
        accel_0_100: 2.6,
        drivetrain: "RWD",
        engine_desc: "3.2L Twin-Turbo Flat-6",
        aero_downforce: "Cl 2.60 / Cd 0.55",
        brakes_desc: "Carbon-Carbon 380mm",
        history_bio: "Overall victor of the 1998 24 Hours of Le Mans. Crafted with a full carbon monocoque and analog unassisted steering, mastering the Mulsanne Straight.",
        stats: (0.98, 0.98, 0.93, 0.40, 0.95, 0.94),
        visual_type: VehicleVisualType::TouringGT { widebody: true, gt_wing: true, diffuser: true },
        base_car_choice: CarChoice::GT1Legend,
        primary_color: Color::new(0.95, 0.95, 0.98, 1.0),
        secondary_color: Color::new(0.15, 0.35, 0.85, 1.0),
    },
    RealCarModel {
        id: "gt_mclaren_f1_gtr_lt",
        name: "McLaren F1 GTR Longtail",
        manufacturer: "McLaren",
        year: 1997,
        module_id: "gt",
        category_name: "GT1 Legend",
        tier: 4,
        bhp: 600,
        torque_nm: 651,
        weight_kg: 915,
        top_speed_kmh: 338,
        accel_0_100: 2.5,
        drivetrain: "RWD",
        engine_desc: "6.0L BMW Motorsport V12 NA",
        aero_downforce: "Cl 2.50 / Cd 0.52",
        brakes_desc: "Carbon-Carbon 4-Piston",
        history_bio: "Legendary central cockpit layout with an elongated rear deck designed to minimize aerodynamic drag, powered by Paul Rosche's atmospheric BMW V12.",
        stats: (0.98, 0.99, 0.92, 0.42, 0.94, 0.92),
        visual_type: VehicleVisualType::TouringGT { widebody: true, gt_wing: true, diffuser: true },
        base_car_choice: CarChoice::GT1Legend,
        primary_color: Color::new(0.95, 0.45, 0.05, 1.0),
        secondary_color: Color::new(0.12, 0.12, 0.15, 1.0),
    },
    RealCarModel {
        id: "gt_mercedes_clk_gtr",
        name: "Mercedes-Benz CLK GTR",
        manufacturer: "Mercedes-AMG",
        year: 1997,
        module_id: "gt",
        category_name: "GT1 Legend",
        tier: 4,
        bhp: 630,
        torque_nm: 700,
        weight_kg: 1000,
        top_speed_kmh: 332,
        accel_0_100: 2.6,
        drivetrain: "RWD",
        engine_desc: "6.0L AMG V12 Atmospheric",
        aero_downforce: "Cl 2.55 / Cd 0.54",
        brakes_desc: "Carbon Discs 6-Piston",
        history_bio: "Dominant 1997 FIA GT World Champion designed, fabricated, and winning on track in just 128 days from project initiation.",
        stats: (0.97, 0.97, 0.93, 0.44, 0.93, 0.93),
        visual_type: VehicleVisualType::TouringGT { widebody: true, gt_wing: true, diffuser: true },
        base_car_choice: CarChoice::GT1Legend,
        primary_color: Color::new(0.70, 0.72, 0.76, 1.0),
        secondary_color: Color::new(0.10, 0.10, 0.12, 1.0),
    },
    RealCarModel {
        id: "gt_nissan_r390_gt1",
        name: "Nissan R390 GT1",
        manufacturer: "Nissan NISMO",
        year: 1998,
        module_id: "gt",
        category_name: "GT1 Legend",
        tier: 4,
        bhp: 641,
        torque_nm: 706,
        weight_kg: 1029,
        top_speed_kmh: 340,
        accel_0_100: 2.7,
        drivetrain: "RWD",
        engine_desc: "3.5L VRH35L Twin-Turbo V8",
        aero_downforce: "Cl 2.48 / Cd 0.53",
        brakes_desc: "AP Racing Carbon",
        history_bio: "Built with TWR for the 1998 24 Hours of Le Mans, securing 3rd overall through relentless powertrain reliability and aerodynamic balance.",
        stats: (0.98, 0.97, 0.91, 0.45, 0.92, 0.91),
        visual_type: VehicleVisualType::TouringGT { widebody: true, gt_wing: true, diffuser: true },
        base_car_choice: CarChoice::GT1Legend,
        primary_color: Color::new(0.15, 0.25, 0.65, 1.0),
        secondary_color: Color::new(0.90, 0.20, 0.15, 1.0),
    },

    // Tier 5: Hypercar Prototype / LMH & LMDh
    RealCarModel {
        id: "gt_ferrari_499p",
        name: "Ferrari 499P LMH",
        manufacturer: "Ferrari",
        year: 2023,
        module_id: "gt",
        category_name: "Hypercar Prototype",
        tier: 5,
        bhp: 680,
        torque_nm: 820,
        weight_kg: 1030,
        top_speed_kmh: 345,
        accel_0_100: 2.3,
        drivetrain: "AWD Hybrid",
        engine_desc: "3.0L Twin-Turbo V6 + Front MGU",
        aero_downforce: "Cl 3.15 / Cd 0.58",
        brakes_desc: "Brembo Carbon-Carbon",
        history_bio: "Back-to-back 24 Hours of Le Mans winner (2023, 2024). Full ground effect underbody tunnels with intelligent front-axle electric deployment.",
        stats: (0.99, 0.99, 0.98, 0.35, 0.98, 0.99),
        visual_type: VehicleVisualType::TouringGT { widebody: true, gt_wing: true, diffuser: true },
        base_car_choice: CarChoice::HypercarPrototype,
        primary_color: Color::new(0.85, 0.08, 0.08, 1.0),
        secondary_color: Color::new(1.0, 0.85, 0.10, 1.0),
    },
    RealCarModel {
        id: "gt_porsche_963",
        name: "Porsche 963 LMDh",
        manufacturer: "Porsche Penske",
        year: 2023,
        module_id: "gt",
        category_name: "Hypercar Prototype",
        tier: 5,
        bhp: 670,
        torque_nm: 780,
        weight_kg: 1030,
        top_speed_kmh: 342,
        accel_0_100: 2.4,
        drivetrain: "RWD Hybrid",
        engine_desc: "4.6L Twin-Turbo V8 + Bosch Hybrid",
        aero_downforce: "Cl 3.05 / Cd 0.57",
        brakes_desc: "Brembo Carbon Spec",
        history_bio: "IMSA and WEC endurance title contender built on the Multimatic monocoque with a twin-turbo V8 derived from the 918 Spyder.",
        stats: (0.99, 0.98, 0.97, 0.38, 0.97, 0.97),
        visual_type: VehicleVisualType::TouringGT { widebody: true, gt_wing: true, diffuser: true },
        base_car_choice: CarChoice::HypercarPrototype,
        primary_color: Color::new(0.92, 0.92, 0.95, 1.0),
        secondary_color: Color::new(0.85, 0.10, 0.10, 1.0),
    },
    RealCarModel {
        id: "gt_toyota_gr010",
        name: "Toyota GR010 Hybrid",
        manufacturer: "Toyota Gazoo Racing",
        year: 2021,
        module_id: "gt",
        category_name: "Hypercar Prototype",
        tier: 5,
        bhp: 671,
        torque_nm: 850,
        weight_kg: 1040,
        top_speed_kmh: 344,
        accel_0_100: 2.3,
        drivetrain: "AWD Hybrid",
        engine_desc: "3.5L Twin-Turbo V6 Hybrid",
        aero_downforce: "Cl 3.20 / Cd 0.59",
        brakes_desc: "Akebono Monobloc Carbon",
        history_bio: "Pioneered the LMH regulations, dominating World Endurance Championships with supreme hybrid regeneration and wet weather traction.",
        stats: (0.99, 0.99, 0.98, 0.34, 0.98, 0.99),
        visual_type: VehicleVisualType::TouringGT { widebody: true, gt_wing: true, diffuser: true },
        base_car_choice: CarChoice::HypercarPrototype,
        primary_color: Color::new(0.10, 0.10, 0.12, 1.0),
        secondary_color: Color::new(0.90, 0.10, 0.10, 1.0),
    },
    RealCarModel {
        id: "gt_cadillac_v_series_r",
        name: "Cadillac V-Series.R",
        manufacturer: "Cadillac Racing",
        year: 2023,
        module_id: "gt",
        category_name: "Hypercar Prototype",
        tier: 5,
        bhp: 670,
        torque_nm: 760,
        weight_kg: 1030,
        top_speed_kmh: 340,
        accel_0_100: 2.4,
        drivetrain: "RWD Hybrid",
        engine_desc: "5.5L Naturally Aspirated DOHC V8",
        aero_downforce: "Cl 3.02 / Cd 0.58",
        brakes_desc: "Brembo Carbon",
        history_bio: "Celebrated for the visceral roar of its naturally aspirated 5.5L cross-plane V8, married to Dallara chassis dynamics and hybrid boost.",
        stats: (0.98, 0.98, 0.96, 0.40, 0.96, 0.96),
        visual_type: VehicleVisualType::TouringGT { widebody: true, gt_wing: true, diffuser: true },
        base_car_choice: CarChoice::HypercarPrototype,
        primary_color: Color::new(0.95, 0.80, 0.15, 1.0),
        secondary_color: Color::new(0.12, 0.12, 0.15, 1.0),
    },

    // =========================================================================
    // MODULE 2: NASCAR STOCK CAR RACING
    // =========================================================================
    // Tier 1: Street Stock V8
    RealCarModel {
        id: "nascar_monte_carlo_ss",
        name: "Chevrolet Monte Carlo Street Stock",
        manufacturer: "Chevrolet",
        year: 1988,
        module_id: "nascar",
        category_name: "Street Stock V8",
        tier: 1,
        bhp: 450,
        torque_nm: 610,
        weight_kg: 1450,
        top_speed_kmh: 245,
        accel_0_100: 4.2,
        drivetrain: "RWD",
        engine_desc: "350ci Small Block Chevy V8",
        aero_downforce: "Cl 0.35 / Cd 0.58",
        brakes_desc: "Steel 300mm Heavy-Duty Drum/Disc",
        history_bio: "Grassroots short-track legend. Heavy steel body and spool rear differential teaching pure momentum preservation on tight dirt and asphalt bullrings.",
        stats: (0.70, 0.74, 0.72, 0.85, 0.70, 0.45),
        visual_type: VehicleVisualType::StockCar { tall_wing: false, roof_fins: false, window_net: true },
        base_car_choice: CarChoice::StockCar,
        primary_color: Color::new(0.20, 0.45, 0.85, 1.0),
        secondary_color: Color::new(0.95, 0.85, 0.15, 1.0),
    },
    RealCarModel {
        id: "nascar_mustang_street_stock",
        name: "Ford Mustang Street Stock",
        manufacturer: "Ford",
        year: 1993,
        module_id: "nascar",
        category_name: "Street Stock V8",
        tier: 1,
        bhp: 450,
        torque_nm: 615,
        weight_kg: 1420,
        top_speed_kmh: 248,
        accel_0_100: 4.1,
        drivetrain: "RWD",
        engine_desc: "351 Windsor V8",
        aero_downforce: "Cl 0.36 / Cd 0.57",
        brakes_desc: "Steel Wilwood 4-Piston",
        history_bio: "Fox-body silhouette housing a carbureted Windsor V8. Slightly lighter nose gives keen turn-in on flat bullrings.",
        stats: (0.71, 0.75, 0.73, 0.84, 0.71, 0.46),
        visual_type: VehicleVisualType::StockCar { tall_wing: false, roof_fins: false, window_net: true },
        base_car_choice: CarChoice::StockCar,
        primary_color: Color::new(0.85, 0.15, 0.15, 1.0),
        secondary_color: Color::new(0.95, 0.95, 0.98, 1.0),
    },
    // Tier 2: Late Model
    RealCarModel {
        id: "nascar_super_late_model",
        name: "Super Late Model Camaro",
        manufacturer: "Chevrolet",
        year: 2022,
        module_id: "nascar",
        category_name: "Late Model Stock",
        tier: 2,
        bhp: 550,
        torque_nm: 680,
        weight_kg: 1220,
        top_speed_kmh: 275,
        accel_0_100: 3.4,
        drivetrain: "RWD",
        engine_desc: "Custom Built 358ci V8",
        aero_downforce: "Cl 0.65 / Cd 0.52",
        brakes_desc: "AP Racing Short Track 4-Piston",
        history_bio: "Tubular perimeter spaceframe chassis engineered for immense mid-corner speed and inside front tire lift on banked asphalt ovals.",
        stats: (0.82, 0.86, 0.82, 0.88, 0.80, 0.60),
        visual_type: VehicleVisualType::StockCar { tall_wing: false, roof_fins: false, window_net: true },
        base_car_choice: CarChoice::StockCar,
        primary_color: Color::new(0.95, 0.50, 0.10, 1.0),
        secondary_color: Color::new(0.10, 0.10, 0.15, 1.0),
    },
    // Tier 3: ARCA
    RealCarModel {
        id: "nascar_arca_chevy_ss",
        name: "Chevrolet SS ARCA Spec",
        manufacturer: "Chevrolet",
        year: 2020,
        module_id: "nascar",
        category_name: "ARCA Menards Series",
        tier: 3,
        bhp: 650,
        torque_nm: 720,
        weight_kg: 1450,
        top_speed_kmh: 305,
        accel_0_100: 3.2,
        drivetrain: "RWD",
        engine_desc: "396ci Ilmor Spec V8",
        aero_downforce: "Cl 0.75 / Cd 0.48",
        brakes_desc: "Heavy Stock Carbon-Metallic 6-Piston",
        history_bio: "Stepping stone to national touring divisions. Employs composite body panels over Gen-6 chassis with potent drafting wake dynamics.",
        stats: (0.88, 0.87, 0.84, 0.86, 0.83, 0.68),
        visual_type: VehicleVisualType::StockCar { tall_wing: false, roof_fins: true, window_net: true },
        base_car_choice: CarChoice::StockCar,
        primary_color: Color::new(0.12, 0.45, 0.85, 1.0),
        secondary_color: Color::new(1.0, 0.90, 0.10, 1.0),
    },
    // Tier 4: Craftsman Truck
    RealCarModel {
        id: "nascar_silverado_truck",
        name: "Chevrolet Silverado RST Truck",
        manufacturer: "Chevrolet",
        year: 2023,
        module_id: "nascar",
        category_name: "Craftsman Truck Series",
        tier: 4,
        bhp: 700,
        torque_nm: 750,
        weight_kg: 1500,
        top_speed_kmh: 310,
        accel_0_100: 3.1,
        drivetrain: "RWD",
        engine_desc: "358ci NASCAR Spec V8",
        aero_downforce: "Cl 0.82 / Cd 0.55",
        brakes_desc: "Heavy-Duty Superspeedway Spec 6-Piston",
        history_bio: "Massive bluff aerodynamic drag creates immense drafting pull, leading to breathtaking 3-wide pack racing and bump drafting.",
        stats: (0.91, 0.89, 0.85, 0.86, 0.85, 0.72),
        visual_type: VehicleVisualType::StockCar { tall_wing: false, roof_fins: true, window_net: true },
        base_car_choice: CarChoice::StockCar,
        primary_color: Color::new(0.90, 0.10, 0.15, 1.0),
        secondary_color: Color::new(0.15, 0.15, 0.18, 1.0),
    },
    // Tier 5: Trans-Am TA1
    RealCarModel {
        id: "nascar_corvette_ta1",
        name: "Chevrolet Corvette C7 TA1",
        manufacturer: "Chevrolet",
        year: 2023,
        module_id: "nascar",
        category_name: "Trans-Am TA1",
        tier: 5,
        bhp: 850,
        torque_nm: 880,
        weight_kg: 1260,
        top_speed_kmh: 320,
        accel_0_100: 2.8,
        drivetrain: "RWD",
        engine_desc: "5.9L Pushrod V8 (850 BHP @ 8,800 RPM)",
        aero_downforce: "Cl 1.20 / Cd 0.50",
        brakes_desc: "AP Racing 6-Piston 380mm",
        history_bio: "The apex of analog American spaceframe racing. 850 horsepower breathing through un-muffled boom tubes with giant rear wings.",
        stats: (0.97, 0.90, 0.86, 0.88, 0.88, 0.78),
        visual_type: VehicleVisualType::StockCar { tall_wing: true, roof_fins: true, window_net: true },
        base_car_choice: CarChoice::StockCar,
        primary_color: Color::new(0.95, 0.85, 0.10, 1.0),
        secondary_color: Color::new(0.10, 0.10, 0.12, 1.0),
    },

    // =========================================================================
    // MODULE 3: RALLYCROSS & ALL-TERRAIN
    // =========================================================================
    // Tier 1: Rally Junior FWD
    RealCarModel {
        id: "rally_peugeot_208_rally4",
        name: "Peugeot 208 Rally4",
        manufacturer: "Peugeot",
        year: 2021,
        module_id: "rally",
        category_name: "Rally Junior FWD",
        tier: 1,
        bhp: 208,
        torque_nm: 290,
        weight_kg: 1080,
        top_speed_kmh: 195,
        accel_0_100: 5.4,
        drivetrain: "FWD",
        engine_desc: "1.2L PureTech 3-Cyl Turbo",
        aero_downforce: "Cl 0.30 / Cd 0.46",
        brakes_desc: "Brembo 4-Piston Gravel/Tarmac",
        history_bio: "Front-wheel-drive academy star. Teaches precision Scandinavian flicks, trail-braking rotation, and lift-off oversteer on gravel.",
        stats: (0.65, 0.72, 0.78, 0.76, 0.74, 0.40),
        visual_type: VehicleVisualType::RallyHatch { roof_scoop: true, mudflaps: true, large_wing: false },
        base_car_choice: CarChoice::RallyCar,
        primary_color: Color::new(0.20, 0.50, 0.95, 1.0),
        secondary_color: Color::new(0.95, 0.95, 0.98, 1.0),
    },
    // Tier 2: WRC / RX Supercar
    RealCarModel {
        id: "rally_hyundai_i20_rx",
        name: "Hyundai i20 RX Supercar",
        manufacturer: "Hyundai",
        year: 2022,
        module_id: "rally",
        category_name: "WRC / RX Supercar",
        tier: 2,
        bhp: 380,
        torque_nm: 550,
        weight_kg: 1240,
        top_speed_kmh: 220,
        accel_0_100: 2.3,
        drivetrain: "AWD",
        engine_desc: "1.6L Direct-Injection Turbo + ALS",
        aero_downforce: "Cl 1.10 / Cd 0.52",
        brakes_desc: "Alcon Water-Cooled 4-Piston",
        history_bio: "Violent 0-100 km/h in 2.3 seconds with permanent mechanical AWD and relentless anti-lag explosions powering full-lock 4-wheel drifts.",
        stats: (0.80, 0.96, 0.92, 0.88, 0.90, 0.75),
        visual_type: VehicleVisualType::RallyHatch { roof_scoop: true, mudflaps: true, large_wing: true },
        base_car_choice: CarChoice::RallyCar,
        primary_color: Color::new(0.40, 0.70, 0.95, 1.0),
        secondary_color: Color::new(0.85, 0.15, 0.15, 1.0),
    },
    // Tier 3: Group B
    RealCarModel {
        id: "rally_audi_sport_quattro_s1",
        name: "Audi Sport Quattro S1 E2",
        manufacturer: "Audi",
        year: 1985,
        module_id: "rally",
        category_name: "Group B Beast",
        tier: 3,
        bhp: 550,
        torque_nm: 590,
        weight_kg: 1090,
        top_speed_kmh: 245,
        accel_0_100: 2.6,
        drivetrain: "AWD",
        engine_desc: "2.1L 5-Cylinder Turbo 20V",
        aero_downforce: "Cl 1.45 / Cd 0.60",
        brakes_desc: "AP Racing 4-Piston Slotted",
        history_bio: "Mythical monster of rally's golden era. Massive KKK turbo boost onset and distinctive 5-cylinder warble with extreme aerodynamic wings.",
        stats: (0.88, 0.97, 0.88, 0.95, 0.86, 0.82),
        visual_type: VehicleVisualType::RallyHatch { roof_scoop: true, mudflaps: true, large_wing: true },
        base_car_choice: CarChoice::RallyCar,
        primary_color: Color::new(0.95, 0.95, 0.90, 1.0),
        secondary_color: Color::new(0.85, 0.40, 0.10, 1.0),
    },
    // Tier 4: Rally Raid T1+
    RealCarModel {
        id: "rally_toyota_hilux_t1_plus",
        name: "Toyota GR DKR Hilux T1+",
        manufacturer: "Toyota",
        year: 2023,
        module_id: "rally",
        category_name: "Rally Raid T1+",
        tier: 4,
        bhp: 450,
        torque_nm: 660,
        weight_kg: 2000,
        top_speed_kmh: 175,
        accel_0_100: 4.8,
        drivetrain: "4WD",
        engine_desc: "3.5L Twin-Turbo V6 (Land Cruiser)",
        aero_downforce: "Cl 0.40 / Cd 0.65",
        brakes_desc: "6-Piston Water-Cooled 355mm",
        history_bio: "Dakar Rally conqueror. Massive 37-inch tires and 350mm wheel travel soaking up boulders and giant dunes at top speed without flinching.",
        stats: (0.74, 0.82, 0.86, 0.85, 0.88, 0.50),
        visual_type: VehicleVisualType::SandRail { lightbar: true, whip_antenna: true, paddle_tires: false },
        base_car_choice: CarChoice::RallyCar,
        primary_color: Color::new(0.85, 0.12, 0.15, 1.0),
        secondary_color: Color::new(0.12, 0.12, 0.15, 1.0),
    },
    // Tier 5: Stadium Super Truck
    RealCarModel {
        id: "rally_sst_super_truck",
        name: "Stadium Super Truck V8",
        manufacturer: "SST",
        year: 2023,
        module_id: "rally",
        category_name: "Stadium Super Truck",
        tier: 5,
        bhp: 650,
        torque_nm: 750,
        weight_kg: 1350,
        top_speed_kmh: 235,
        accel_0_100: 3.4,
        drivetrain: "RWD",
        engine_desc: "6.2L Chevrolet LS3 V8",
        aero_downforce: "Cl 0.20 / Cd 0.68",
        brakes_desc: "Wilwood 4-Wheel Disc",
        history_bio: "Spectacle on wheels created by Robby Gordon. Huge body roll, 3-wheel apex cornering, and soaring 60-meter launches off steel ramps.",
        stats: (0.86, 0.92, 0.76, 0.96, 0.82, 0.40),
        visual_type: VehicleVisualType::SandRail { lightbar: false, whip_antenna: true, paddle_tires: false },
        base_car_choice: CarChoice::RallyCar,
        primary_color: Color::new(0.95, 0.45, 0.10, 1.0),
        secondary_color: Color::new(0.10, 0.10, 0.12, 1.0),
    },

    // =========================================================================
    // MODULE 4: EXTREME OFF-ROAD & ARENAS
    // =========================================================================
    // Tier 1: Sand Rail Buggy
    RealCarModel {
        id: "offroad_sand_rail_buggy",
        name: "Can-Am Maverick R Trophy Spec",
        manufacturer: "Can-Am",
        year: 2024,
        module_id: "extreme_offroad",
        category_name: "Sand Rail Buggy",
        tier: 1,
        bhp: 300,
        torque_nm: 380,
        weight_kg: 590,
        top_speed_kmh: 215,
        accel_0_100: 3.5,
        drivetrain: "RWD",
        engine_desc: "Rotax 999T Triple-Cylinder Turbo",
        aero_downforce: "Cl 0.25 / Cd 0.60",
        brakes_desc: "Wilwood Off-Road 4-Piston",
        history_bio: "Ultralight chromoly tube chassis, rear paddle tires, and long-travel Fox live-valve shocks creating massive sand roosts over desert dunes.",
        stats: (0.88, 0.96, 0.82, 0.94, 0.80, 0.42),
        visual_type: VehicleVisualType::SandRail { lightbar: true, whip_antenna: true, paddle_tires: true },
        base_car_choice: CarChoice::SandRail,
        primary_color: Color::new(0.95, 0.80, 0.15, 1.0),
        secondary_color: Color::new(0.10, 0.10, 0.12, 1.0),
    },
    // Tier 2: Trophy Truck
    RealCarModel {
        id: "offroad_baja_trophy_truck",
        name: "Geiser Bros AWD Trophy Truck",
        manufacturer: "Geiser Bros",
        year: 2023,
        module_id: "extreme_offroad",
        category_name: "Trophy Truck 4x4",
        tier: 2,
        bhp: 800,
        torque_nm: 920,
        weight_kg: 2400,
        top_speed_kmh: 225,
        accel_0_100: 3.8,
        drivetrain: "AWD",
        engine_desc: "Custom 442ci Dougans Big Block V8",
        aero_downforce: "Cl 0.30 / Cd 0.72",
        brakes_desc: "Alcon 6-Piston 355mm Heavy-Duty",
        history_bio: "The king of Baja. Skims across 3-foot desert whoops at over 200 km/h with 30 inches of King bypass suspension travel.",
        stats: (0.85, 0.91, 0.84, 0.92, 0.86, 0.45),
        visual_type: VehicleVisualType::SandRail { lightbar: true, whip_antenna: true, paddle_tires: false },
        base_car_choice: CarChoice::SandRail,
        primary_color: Color::new(0.15, 0.40, 0.85, 1.0),
        secondary_color: Color::new(0.95, 0.95, 0.98, 1.0),
    },
    // Tier 3: Arctic Ice Racer
    RealCarModel {
        id: "offroad_subaru_ice_racer",
        name: "Subaru WRX STI Ice Racer",
        manufacturer: "Subaru",
        year: 2021,
        module_id: "extreme_offroad",
        category_name: "Arctic Ice Racer",
        tier: 3,
        bhp: 500,
        torque_nm: 650,
        weight_kg: 1220,
        top_speed_kmh: 230,
        accel_0_100: 2.8,
        drivetrain: "AWD",
        engine_desc: "2.0L EJ207 Boxer-4 Turbo + ALS",
        aero_downforce: "Cl 0.90 / Cd 0.54",
        brakes_desc: "Brembo Competition with Studded Ice Setup",
        history_bio: "Equipped with 600 tungsten carbide tire studs per tire, pulling sustained 60-degree slip angles on mirror-sheen frozen lakes.",
        stats: (0.84, 0.94, 0.90, 0.98, 0.88, 0.65),
        visual_type: VehicleVisualType::RallyHatch { roof_scoop: true, mudflaps: true, large_wing: true },
        base_car_choice: CarChoice::RallyCar,
        primary_color: Color::new(0.10, 0.25, 0.75, 1.0),
        secondary_color: Color::new(0.90, 0.75, 0.15, 1.0),
    },
    // Tier 4: Mud Bogger
    RealCarModel {
        id: "offroad_mega_mud_truck",
        name: "Mega Truck V8 Mud Slinger",
        manufacturer: "Custom",
        year: 2022,
        module_id: "extreme_offroad",
        category_name: "Mud Bogger V8",
        tier: 4,
        bhp: 900,
        torque_nm: 1100,
        weight_kg: 2800,
        top_speed_kmh: 160,
        accel_0_100: 4.2,
        drivetrain: "4WD",
        engine_desc: "572ci Supercharged Big Block Chevy",
        aero_downforce: "Cl 0.10 / Cd 0.85",
        brakes_desc: "Pinion Disc Brakes Rockwell 2.5T",
        history_bio: "Tall-riding mud monster fitted with 48-inch agricultural paddle tractor tires, slicing through deep mud slurries with ease.",
        stats: (0.72, 0.90, 0.82, 0.90, 0.75, 0.30),
        visual_type: VehicleVisualType::SandRail { lightbar: true, whip_antenna: true, paddle_tires: false },
        base_car_choice: CarChoice::SandRail,
        primary_color: Color::new(0.35, 0.55, 0.25, 1.0),
        secondary_color: Color::new(0.12, 0.12, 0.15, 1.0),
    },
    // Tier 5: Crusher Monster Truck
    RealCarModel {
        id: "offroad_grave_crusher",
        name: "Grave Digger Spec Monster Jam",
        manufacturer: "Monster Jam",
        year: 2023,
        module_id: "extreme_offroad",
        category_name: "Crusher Monster Truck",
        tier: 5,
        bhp: 1500,
        torque_nm: 1800,
        weight_kg: 5400,
        top_speed_kmh: 165,
        accel_0_100: 3.0,
        drivetrain: "4WD 4WS",
        engine_desc: "540ci Merlin Supercharged V8 (Methanol)",
        aero_downforce: "Cl 0.05 / Cd 0.95",
        brakes_desc: "Severe Duty Pinion Brakes",
        history_bio: "1,500 horsepower supercharged methanol beast on 66-inch BKT tires. 4-wheel steering enables spin-donuts and gigantic arena stadium jumps.",
        stats: (0.80, 0.98, 0.80, 0.95, 0.80, 0.25),
        visual_type: VehicleVisualType::SandRail { lightbar: true, whip_antenna: true, paddle_tires: false },
        base_car_choice: CarChoice::SandRail,
        primary_color: Color::new(0.20, 0.75, 0.25, 1.0),
        secondary_color: Color::new(0.55, 0.15, 0.75, 1.0),
    },

    // =========================================================================
    // MODULE 5: KARTING & MICRO-RACERS
    // =========================================================================
    // Tier 1: Cadet Kart 60cc
    RealCarModel {
        id: "kart_crg_hero_60",
        name: "CRG Hero 60cc Cadet",
        manufacturer: "CRG",
        year: 2023,
        module_id: "kart",
        category_name: "Cadet Kart 60cc",
        tier: 1,
        bhp: 10,
        torque_nm: 12,
        weight_kg: 110,
        top_speed_kmh: 85,
        accel_0_100: 7.5,
        drivetrain: "RWD",
        engine_desc: "60cc 2-Stroke Air-Cooled",
        aero_downforce: "Cl 0.10 / Cd 0.50",
        brakes_desc: "Hydraulic Self-Adjusting Rear Disc",
        history_bio: "The cradle of world motorsport champions. Pure momentum management where avoiding scrubbing speed in corners is the key to victory.",
        stats: (0.50, 0.65, 0.88, 0.45, 0.75, 0.30),
        visual_type: VehicleVisualType::GoKart { exposed_driver: true, side_bumpers: true },
        base_car_choice: CarChoice::Kart,
        primary_color: Color::new(0.12, 0.12, 0.15, 1.0),
        secondary_color: Color::new(0.95, 0.50, 0.10, 1.0),
    },
    // Tier 2: Senior Kart 100cc Direct Drive OK
    RealCarModel {
        id: "kart_tony_kart_racer_ok",
        name: "Tony Kart Racer 401 RR OK",
        manufacturer: "Tony Kart",
        year: 2023,
        module_id: "kart",
        category_name: "Senior Kart 100cc OK",
        tier: 2,
        bhp: 30,
        torque_nm: 22,
        weight_kg: 145,
        top_speed_kmh: 125,
        accel_0_100: 4.2,
        drivetrain: "RWD",
        engine_desc: "125cc Direct Drive 2-Stroke (16,000 RPM)",
        aero_downforce: "Cl 0.15 / Cd 0.52",
        brakes_desc: "OTK BSD High Performance Hydraulic",
        history_bio: "Direct-drive racing weapon without gearbox. Screams to 16,000 RPM, demanding tremendous neck strength and razor-sharp line discipline.",
        stats: (0.68, 0.85, 0.94, 0.42, 0.88, 0.35),
        visual_type: VehicleVisualType::GoKart { exposed_driver: true, side_bumpers: true },
        base_car_choice: CarChoice::Kart,
        primary_color: Color::new(0.20, 0.75, 0.35, 1.0),
        secondary_color: Color::new(0.95, 0.95, 0.98, 1.0),
    },
    // Tier 3: Shifter Kart 125cc KZ2
    RealCarModel {
        id: "kart_birel_art_kz2",
        name: "Birel ART KZ2 125cc Shifter",
        manufacturer: "Birel ART",
        year: 2023,
        module_id: "kart",
        category_name: "Shifter Kart 125cc KZ2",
        tier: 3,
        bhp: 50,
        torque_nm: 35,
        weight_kg: 175,
        top_speed_kmh: 155,
        accel_0_100: 2.8,
        drivetrain: "RWD",
        engine_desc: "125cc 6-Speed Sequential Water-Cooled",
        aero_downforce: "Cl 0.20 / Cd 0.55",
        brakes_desc: "Twin Front Discs + Rear Ventilated Disc",
        history_bio: "Peak karting intensity. 6-speed sequential gearbox firing off 0-100 km/h in under 3 seconds while pulling 3.5G lateral cornering grip.",
        stats: (0.80, 0.96, 0.97, 0.40, 0.96, 0.40),
        visual_type: VehicleVisualType::GoKart { exposed_driver: true, side_bumpers: true },
        base_car_choice: CarChoice::Kart,
        primary_color: Color::new(0.85, 0.12, 0.15, 1.0),
        secondary_color: Color::new(0.95, 0.95, 0.98, 1.0),
    },
    // Tier 4: Racing Lawnmower
    RealCarModel {
        id: "kart_honda_mean_mower",
        name: "Honda Mean Mower V2 Tuned",
        manufacturer: "Honda Racing",
        year: 2020,
        module_id: "kart",
        category_name: "Racing Lawnmower",
        tier: 4,
        bhp: 40,
        torque_nm: 45,
        weight_kg: 200,
        top_speed_kmh: 170,
        accel_0_100: 4.0,
        drivetrain: "RWD",
        engine_desc: "999cc Fireblade CBR1000RR Motor",
        aero_downforce: "Cl 0.05 / Cd 0.75",
        brakes_desc: "4-Pot Goldwing Quad Discs",
        history_bio: "Guinness World Record heritage. High-center-of-gravity tuned lawnmower delivering hilarious lift-off oversteer and frantic curb hopping.",
        stats: (0.78, 0.88, 0.70, 0.92, 0.80, 0.20),
        visual_type: VehicleVisualType::GoKart { exposed_driver: true, side_bumpers: false },
        base_car_choice: CarChoice::Kart,
        primary_color: Color::new(0.85, 0.10, 0.10, 1.0),
        secondary_color: Color::new(0.95, 0.95, 0.95, 1.0),
    },
    // Tier 5: Superkart 250cc Twin GP
    RealCarModel {
        id: "kart_anderson_cs250",
        name: "Anderson CS250 Twin GP",
        manufacturer: "Anderson",
        year: 2023,
        module_id: "kart",
        category_name: "Superkart 250cc GP",
        tier: 5,
        bhp: 100,
        torque_nm: 65,
        weight_kg: 220,
        top_speed_kmh: 245,
        accel_0_100: 2.4,
        drivetrain: "RWD",
        engine_desc: "250cc Twin-Cylinder 2-Stroke (VM Engine)",
        aero_downforce: "Cl 1.60 / Cd 0.48",
        brakes_desc: "Triple Hydraulic Ventilated Carbon",
        history_bio: "Full carbon bodywork aerodynamic monster that races on full-size Grand Prix circuits, capable of out-cornering Formula 3 cars at 245 km/h.",
        stats: (0.92, 0.98, 0.99, 0.35, 0.97, 0.85),
        visual_type: VehicleVisualType::OpenWheel { front_wing_span: 1.0, rear_wing_height: 0.8, halo: false },
        base_car_choice: CarChoice::Kart,
        primary_color: Color::new(0.95, 0.85, 0.10, 1.0),
        secondary_color: Color::new(0.12, 0.12, 0.15, 1.0),
    },
];

/// Returns all vehicles belonging to the specified module ID.
pub fn get_models_for_module(module_id: &str) -> Vec<&'static RealCarModel> {
    let mod_id = match module_id {
        "gt_challenge" | "f1" => "gt",
        other => other,
    };
    ALL_REAL_CARS.iter().filter(|c| c.module_id == mod_id).collect()
}

/// Returns all vehicles belonging to the specified module ID and tier (1..=5).
pub fn get_models_for_module_and_tier(module_id: &str, tier: u8) -> Vec<&'static RealCarModel> {
    let mod_id = match module_id {
        "gt_challenge" | "f1" => "gt",
        other => other,
    };
    ALL_REAL_CARS
        .iter()
        .filter(|c| c.module_id == mod_id && c.tier == tier)
        .collect()
}

/// Returns the category display title for a given module and tier.
pub fn get_tier_name(module_id: &str, tier: u8) -> &'static str {
    let mod_id = match module_id {
        "gt_challenge" | "f1" => "gt",
        other => other,
    };
    match (mod_id, tier) {
        ("gt", 1) => "Tier 1: GT4 Clubsport",
        ("gt", 2) => "Tier 2: GT3 Evo / FIA GT3",
        ("gt", 3) => "Tier 3: GT2 Biturbo",
        ("gt", 4) => "Tier 4: GT1 Legend",
        ("gt", 5) => "Tier 5: Hypercar Prototype",

        ("nascar", 1) => "Tier 1: Street Stock V8",
        ("nascar", 2) => "Tier 2: Late Model Stock",
        ("nascar", 3) => "Tier 3: ARCA Menards Series",
        ("nascar", 4) => "Tier 4: Craftsman Truck",
        ("nascar", 5) => "Tier 5: Trans-Am TA1",

        ("rally", 1) => "Tier 1: Rally Junior FWD",
        ("rally", 2) => "Tier 2: WRC / RX Supercar",
        ("rally", 3) => "Tier 3: Group B Beast",
        ("rally", 4) => "Tier 4: Rally Raid T1+",
        ("rally", 5) => "Tier 5: Stadium Super Truck",

        ("extreme_offroad", 1) => "Tier 1: Sand Rail Buggy",
        ("extreme_offroad", 2) => "Tier 2: Trophy Truck 4x4",
        ("extreme_offroad", 3) => "Tier 3: Arctic Ice Racer",
        ("extreme_offroad", 4) => "Tier 4: Mud Bogger V8",
        ("extreme_offroad", 5) => "Tier 5: Crusher Monster Truck",

        ("kart", 1) => "Tier 1: Cadet Kart 60cc",
        ("kart", 2) => "Tier 2: Senior Kart 100cc OK",
        ("kart", 3) => "Tier 3: Shifter Kart 125cc KZ2",
        ("kart", 4) => "Tier 4: Racing Lawnmower",
        ("kart", 5) => "Tier 5: Superkart 250cc GP",

        _ => "Tier 1: Open Competition",
    }
}

/// Searches for a vehicle model by its string identifier.
pub fn find_model_by_id(id: &str) -> Option<&'static RealCarModel> {
    ALL_REAL_CARS.iter().find(|c| c.id == id)
}

/// Returns the entire master collection of authentic real-world vehicles.
pub fn get_all_models() -> &'static [RealCarModel] {
    ALL_REAL_CARS
}

/// Helper function to check category eligibility for a race.
/// Rule: A car is eligible iff car.tier <= race_required_tier || dev_mode.
#[inline]
pub fn is_car_eligible(car_tier: u8, race_required_tier: u8, dev_mode: bool) -> bool {
    dev_mode || car_tier <= race_required_tier
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_all_modules_have_5_tiers() {
        for m in ["gt", "nascar", "rally", "extreme_offroad", "kart"] {
            for t in 1..=5 {
                let models = get_models_for_module_and_tier(m, t);
                assert!(
                    !models.is_empty(),
                    "Module {} must have at least 1 authentic model for tier {}",
                    m,
                    t
                );
            }
        }
    }

    #[test]
    fn test_category_eligibility_rule() {
        // In dev mode, any car can race anywhere
        assert!(is_car_eligible(5, 1, true));
        assert!(is_car_eligible(1, 1, true));

        // Normal mode: car tier <= race tier
        assert!(is_car_eligible(1, 1, false));
        assert!(is_car_eligible(1, 2, false));
        assert!(is_car_eligible(2, 2, false));
        assert!(is_car_eligible(3, 5, false));

        // Normal mode: superior tier blocked!
        assert!(!is_car_eligible(2, 1, false));
        assert!(!is_car_eligible(3, 2, false));
        assert!(!is_car_eligible(5, 4, false));
    }
}
